#!/usr/bin/env python3
# -*- coding: utf-8 -*-

#imports GPIO, time, MotionSensor functions and PiCamera functions
import RPi.GPIO as gpio
import time
from gpiozero import MotionSensor
from picamera import PiCamera

#assigns GPIO pin to the motion sensor
sensor = MotionSensor(4)

#assign PiCamera to camera variable
camera = PiCamera()


#function called from main to detect motion
def detMotion():
    #sensor waits for motion
    sensor.wait_for_motion()
    
    #take picture
    camera.capture('/tmp/picture.jpg')
    
    #sleep timer so sensor can reset itself
    time.sleep(5)
    

#enter endless loop to call detMotion function
while True:
    detMotion()
